Description: Spotify SAM Tracker - Query DynamoDB for Top

Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.10
      CodeUri: code
      MemorySize: 256
      Timeout: 900
      Environment:
        Variables:
          Table: !ImportValue spotify-tracker-sam-TableName
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue spotify-tracker-sam-TableName