Description: Lambda Function POC

Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Lambda Function

Parameters:
  Bucket:
    Type: String
    Default: None
  PandasLayer:
    Type: String
    Default: arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1
  Table:
    Type: String
    Default: None
  Topic:
    Type: String
    Default: None

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: code
      Timeout: 120
      Layers:
        - !ImportValue spotify-tracker-sam-Parameters-1VQDTTBKRD7WJ-PandasLayerArn
      Environment:
        Variables:
          Bucket: !ImportValue spotify-tracker-sam-Bucket
          Table: !ImportValue spotify-tracker-sam-TableName
          Topic: !ImportValue spotify-tracker-sam-TopicArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue spotify-tracker-sam-TableName
        - S3CrudPolicy:
            BucketName: !ImportValue spotify-tracker-sam-Bucket
        - Statement:
          - Effect: Allow
            Action:
              - 'sns:publish'
            Resource:
              - !ImportValue spotify-tracker-sam-TopicArn