Description: S3 Bucket

Outputs:
  Bucket:
    Value: !Ref Bucket
    Export:
      Name: spotify-tracker-sam-Bucket

Resources:
  Bucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Delete Noncurrent
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 5
          - Id: Delete All AWSDynamoDB
            Status: Enabled
            Prefix: outputs/AWSDynamoDB/
            ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
          - Id: Delete All NowPlaying Code - 1 Day
            Status: Enabled
            Prefix: code/
            ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
