Description: Parameters

Outputs:
  SpotifyClientID:
    Value: !Ref SpotifyClientID
    Export:
      Name: !Sub ${AWS::StackName}-SpotifyClientID

  SpotifyClientSecret:
    Value: !Ref SpotifyClientSecret
    Export:
      Name: !Sub ${AWS::StackName}-SpotifyClientSecret

  SpotifyRefreshToken:
    Value: !Ref SpotifyRefreshToken
    Export:
      Name: !Sub ${AWS::StackName}-SpotifyRefreshToken

  CurrentTrack:
    Value: !Ref CurrentTrack
    Export:
      Name: !Sub ${AWS::StackName}-CurrentTrack

  PreviousEntryEpochTime:
    Value: !Ref PreviousEntryEpochTime
    Export:
      Name: !Sub ${AWS::StackName}-PreviousEntryEpochTime

  ExportTableArn:
    Value: !Ref ExportTableArn
    Export:
      Name: !Sub ${AWS::StackName}-ExportTableArn

  RequestsLayerArn:
    Value: arn:aws:lambda:us-east-1:195663387853:layer:Requests:8
    Export:
      Name: !Sub ${AWS::StackName}-RequestsLayerArn

  Key:
    Value: now_playing.zip
    Export:
      Name: !Sub ${AWS::StackName}-Key

  EventBridgeSchedule:
    Value: rate(2 minutes)
    Export:
      Name: !Sub ${AWS::StackName}-EventBridgeSchedule

  EventBridgeState:
    Value: ENABLED
    Export:
      Name: !Sub ${AWS::StackName}-EventBridgeState

Resources:
  SpotifyClientID:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Client ID
      Tier: Standard
      Type: String
      Value: None

  SpotifyClientSecret:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Secret
      Tier: Standard
      Type: String
      Value: None

  SpotifyRefreshToken:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Refresh Token
      Tier: Standard
      Type: String
      Value: None

  CurrentTrack:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Current Track ID
      Tier: Standard
      Type: String
      Value: None

  PreviousEntryEpochTime:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DynamoDB Previous Entry's EpochTime
      Tier: Standard
      Type: String
      Value: None

  ExportTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DynamoDB Current Export Arn
      Tier: Standard
      Type: String
      Value: None