Description: Serverless Lambda Function
Parameters:
  Bucket:
    Type: String
    Default: None
  CallbackURL:
    Type: String
    Default: None
  CurrentTrack:
    Type: String
    Default: None
  ExportTableArn:
    Type: String
    Default: None
  PreviousEntryEpochTime:
    Type: String
    Default: None
  RedirectUri:
    Type: String
    Default: None
  SpotifyClientID:
    Type: String
    Default: None
  SpotifyClientSecret:
    Type: String
    Default: None
  SpotifyRefreshToken:
    Type: String
    Default: None
  Table:
    Type: String
    Default: None
  Topic:
    Type: String
    Default: None

Resources:
  WaitConditionHandle:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
    Properties: {}