AWSTemplateFormatVersion: '2010-09-09'
Description: Topics for Spotify SAM

Parameters:
  Email:
    Type: String
    Description: Enter the e-mail for error notifications.

Outputs:
  TopicARN:
    Value: !Ref Topic
    Export:
      Name: spotify-tracker-sam-TopicArn

Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !ImportValue spotify-tracker-sam-Email
      Protocol: email
      TopicArn: !Ref Topic