Description: Lambda Function POC

Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Lambda Function

Parameters:
  Table:
    Type: String
    Default: None
  Bucket:
    Type: String
    Default: None
  Topic:
    Type: String
    Default: None
  ExportTableArn:
    Type: String
    Default: None

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: code
      Timeout: 120
      Environment:
        Variables:
          TableArn: !Sub
            - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
            - tableName: !ImportValue spotify-tracker-sam-TableName
          Bucket: !Ref Bucket
          ExportArn: !Ref ExportTableArn
          Topic: !ImportValue spotify-tracker-sam-TopicArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue spotify-tracker-sam-TableName
        - S3CrudPolicy:
            BucketName: !Ref Bucket
        - Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:ExportTableToPointInTime'
            Resource: !Sub
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
              - tableName: !ImportValue spotify-tracker-sam-TableName
        - Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:DescribeExport'
            Resource: !Sub
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}/export/*
              - tableName: !ImportValue spotify-tracker-sam-TableName

        - Statement:
          - Effect: Allow
            Action:
              - 'sns:publish'
            Resource:
              - !ImportValue spotify-tracker-sam-TopicArn
          - Effect: Allow
            Action:
              - 'ssm:DescribeParameters'
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
              - 'ssm:PutParameter'
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ExportTableArn}