Description: Lambda Function POC

Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Lambda Function

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.10
      CodeUri: code
      Timeout: 120
      Environment:
        Variables:
          TableArn: !Sub
            - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
            - tableName: !ImportValue spotify-tracker-sam-TableName
          Bucket: !ImportValue spotify-tracker-sam-Bucket
          ExportArn: !ImportValue spotify-tracker-sam-Parameters-1VQDTTBKRD7WJ-ExportTableArn
          Topic: !ImportValue spotify-tracker-sam-TopicArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue spotify-tracker-sam-TableName

        - S3CrudPolicy:
            BucketName: !ImportValue spotify-tracker-sam-Bucket

        - Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:ExportTableToPointInTime'
            Resource: !Sub
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
              - tableName: !ImportValue spotify-tracker-sam-TableName

        - Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:DescribeExport'
            Resource: !Sub
              - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}/export/*
              - tableName: !ImportValue spotify-tracker-sam-TableName

        - Statement:
          - Effect: Allow
            Action:
              - 'sns:publish'
            Resource:
              - !ImportValue spotify-tracker-sam-TopicArn

        - Statement:
          - Effect: Allow
            Action:
              - 'ssm:DescribeParameters'
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
              - 'ssm:PutParameter'
            Resource:
              - !Sub
                  - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ExportTableArn}
                  - ExportTableArn: !ImportValue spotify-tracker-sam-Parameters-1VQDTTBKRD7WJ-ExportTableArn