version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "spotify-tracker-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-148nh4a4hjibx"
s3_prefix = "spotify-tracker-sam"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []