AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This template deploys a basic Spotify Now Playing tracker to DynamoDB.

Parameters:
  Email:
    Type: String
    Description: Enter the e-mail for error notifications.
  CallbackURL:
    Type: String
    Description: Enter the callback URL
  RequestsLayerArn:
    Type: String
    Default: arn:aws:lambda:us-east-1:195663387853:layer:Requests:8

  VpcId:
    Type: AWS::EC2::VPC::Id

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: A list of subnets for the Auto Scaling group

Outputs:
  Email:
    Value: !Ref Email
    Export:
      Name: !Sub ${AWS::StackName}-Email
  RedirectUri:
    Value: !Ref CallbackURL
    Export:
      Name: !Sub ${AWS::StackName}-RedirectUri

  CallbackURL:
    Value: !Ref CallbackURL
    Export:
      Name: !Sub ${AWS::StackName}-CallbackURL

  TableName:
    Value: !Ref DynamoDB
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  TableArn:
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDB}
    Export:
      Name: !Sub ${AWS::StackName}-TableArn

  TableNameRefreshToken:
    Value: !Ref DynamoDBRefreshToken
    Export:
      Name: !Sub ${AWS::StackName}-TableNameRefreshToken

  TableArnRefreshToken:
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBRefreshToken}
    Export:
      Name: !Sub ${AWS::StackName}-TableArnRefreshToken

  TableNameTop:
    Value: !Ref DynamoDBTop
    Export:
      Name: !Sub ${AWS::StackName}-TableNameTop

  TableArnTop:
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTop}
    Export:
      Name: !Sub ${AWS::StackName}-TableArnTop

  TopicNested:
    Value:
      Fn::GetAtt:
        - StackTopics
        - Outputs.TopicARN
    Export:
      Name: !Sub ${AWS::StackName}-TopicNested

  VpcId:
    Value: !Ref VpcId
    Export:
      Name: !Sub ${AWS::StackName}-VpcId

  Subnets:
    Value: !Join [",", !Ref Subnets]
    Export:
      Name: !Sub ${AWS::StackName}-Subnets

Resources:
  DynamoDB:
    DeletionPolicy: Retain
    Type: 'AWS::Serverless::SimpleTable'

  DynamoDBRefreshToken:
    DeletionPolicy: Retain
    Type: 'AWS::Serverless::SimpleTable'

  DynamoDBTop:
    DeletionPolicy: Retain
    Type: 'AWS::Serverless::SimpleTable'

  StackTopics:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Email : !Ref Email
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/topics.yaml

  Parameters:
    DeletionPolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/parameters.yaml

  StackBucket:
    DeletionPolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/bucket.yaml

  AutoScalingGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/launch-template.yaml
      Parameters:
        VpcId: !ImportValue spotify-tracker-sam-VpcId
        Subnets: !ImportValue spotify-tracker-sam-Subnets