AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This template deploys a basic Spotify Now Playing tracker to DynamoDB.

Parameters:
  Email:
    Type: String
    Description: Enter the e-mail for error notifications.
  CallbackURL:
    Type: String
    Description: Enter the callback URL
  RequestsLayerArn:
    Type: String
    Default: arn:aws:lambda:us-east-1:195663387853:layer:Requests:8

Outputs:
  RedirectUri:
    Value: !Ref CallbackURL
  Table:
    Value: !Ref DynamoDB
  TopicNested:
    Value:
      Fn::GetAtt:
        - StackTopics
        - Outputs.TopicARN
Resources:
  DynamoDB:
    Type: 'AWS::Serverless::SimpleTable'

  StackTopics:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Email : !Ref Email
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/topics.yaml

  StackParameters:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/parameters.yaml

  StackBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/bucket.yaml

  StackLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        CallbackURL: !Ref CallbackURL
        CurrentTrack: !Sub ${StackParameters.Outputs.CurrentTrack}
        PreviousEntryEpochTime: !Sub ${StackParameters.Outputs.PreviousEntryEpochTime}
        RedirectUri: !Ref CallbackURL
        SpotifyClientID: !Sub ${StackParameters.Outputs.SpotifyClientID}
        SpotifyClientSecret: !Sub ${StackParameters.Outputs.SpotifyClientSecret}
        SpotifyRefreshToken: !Sub ${StackParameters.Outputs.SpotifyRefreshToken}
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  LambdaNowPlaying:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/1_NowPlaying/template.yaml
      Parameters:
        CallbackURL: !Ref CallbackURL
        CurrentTrack: !Sub ${StackParameters.Outputs.CurrentTrack}
        EventBridgeSchedule: rate(2 minutes)
        EventBridgeState: ENABLED #DISABLED
        PreviousEntryEpochTime: !Sub ${StackParameters.Outputs.PreviousEntryEpochTime}
        RedirectUri: !Ref CallbackURL
        RequestsLayerArn: !Ref RequestsLayerArn
        SpotifyClientID: !Sub ${StackParameters.Outputs.SpotifyClientID}
        SpotifyClientSecret: !Sub ${StackParameters.Outputs.SpotifyClientSecret}
        SpotifyRefreshToken: !Sub ${StackParameters.Outputs.SpotifyRefreshToken}
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  StackLambdaReportCurrentMonth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        Bucket: !Sub ${StackBucket.Outputs.Bucket}
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  StackLambdaUtilityMigrateEpoch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  StackLambdaUtilityMigrateYearMonth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  StackLambdaUtilityDeleteById:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}