AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This template deploys a basic Spotify Now Playing tracker to DynamoDB.
Parameters:
  Email:
    Type: String
    Description: Enter the e-mail for error notifications.
  CallbackURL:
    Type: String
    Description: Enter the callback URL
Outputs:
  ClientID:
    Value: !Ref ParameterSpotifyClientID
  ClientSecret:
    Value: !Ref ParameterSpotifyClientSecret
  RefreshToken:
    Value: !Ref ParameterSpotifyRefreshToken
  RedirectUri:
    Value: !Ref CallbackURL
  CurrentTrack:
    Value: !Ref ParameterCurrentTrack
  Table:
    Value: !Ref DynamoDB
  Topic:
    Value: !Ref Topic
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: python
      Timeout: 15
      Events:
        EventBridge:
            Type: Schedule
            Properties:
              Schedule: rate(3 minutes)
              Enabled: true
              Name: 'EventBridge'
        PostAPI:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
        GetAPI:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt Topic.TopicName
        - CloudFormationDescribeStacksPolicy: {}
        - Statement:
          - Effect: Allow
            Action:
              - 'ssm:DescribeParameters'
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
              - 'ssm:PutParameter'
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterSpotifyClientID}
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterSpotifyClientSecret}
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterSpotifyRefreshToken}
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ParameterCurrentTrack}
          - Effect: Allow
            Action:
              - 'events:PutRule'
            Resource:
              - !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/EventBridge'
  Topic:
    Type: 'AWS::SNS::Topic'
  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref Topic
  DynamoDB:
    Type: 'AWS::Serverless::SimpleTable'
  ParameterSpotifyClientID:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Client ID
      Tier: Standard
      Type: String
      Value: None
  ParameterSpotifyClientSecret:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Secret
      Tier: Standard
      Type: String
      Value: None
  ParameterSpotifyRefreshToken:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Refresh Token
      Tier: Standard
      Type: String
      Value: None
  ParameterCurrentTrack:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Spotify Current Track ID
      Tier: Standard
      Type: String
      Value: None

  LambdaReport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: dynamodb-report
      Timeout: 5
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoDB
      Events:
        EventBridge:
            Type: Schedule
            Properties:
              Schedule: rate(3 minutes)
              Enabled: false
              Name: 'EventBridgeReport'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB