AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This template deploys a basic Spotify Now Playing tracker to DynamoDB.

Parameters:
  Email:
    Type: String
    Description: Enter the e-mail for error notifications.
  CallbackURL:
    Type: String
    Description: Enter the callback URL

Outputs:
  RedirectUri:
    Value: !Ref CallbackURL
  Table:
    Value: !Ref DynamoDB
  TopicNested:
    Value:
      Fn::GetAtt:
        - StackTopics
        - Outputs.TopicARN
Resources:
  DynamoDB:
    Type: 'AWS::Serverless::SimpleTable'

  LambdaReport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: dynamodb-report
      Timeout: 5
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoDB
      Events:
        EventBridge:
            Type: Schedule
            Properties:
              Schedule: rate(3 minutes)
              Enabled: false
              Name: 'EventBridgeReport'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB

  LambdaMigrateEpoch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: migrate-epoch
      Timeout: 840
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoDB
          Topic:
            Fn::GetAtt:
              - StackTopics
              - Outputs.TopicARN
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - StackTopics
                - Outputs.TopicARN

  LambdaDeleteById:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: dynamodb-delete-by-id
      Timeout: 300
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB

  LambdaAddYearMonth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: add-year-month
      Timeout: 840 # 14 minutes
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB

  LambdaDynamoDBScan:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: dynamodb-query
      Timeout: 120 # 14 minutes
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoDB
          Bucket: !GetAtt
            - StackBucket
            - Outputs.Bucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDB
        - S3CrudPolicy:
            BucketName: !GetAtt
              - StackBucket
              - Outputs.Bucket

  StackTopics:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Email : !Ref Email
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/topics.yaml

  StackParameters:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/parameters.yaml

  StackBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/bucket.yaml

  StackLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        CallbackURL: !Ref CallbackURL
        CurrentTrack: !Sub ${StackParameters.Outputs.CurrentTrack}
        PreviousEntryEpochTime: !Sub ${StackParameters.Outputs.PreviousEntryEpochTime}
        RedirectUri: !Ref CallbackURL
        SpotifyClientID: !Sub ${StackParameters.Outputs.SpotifyClientID}
        SpotifyClientSecret: !Sub ${StackParameters.Outputs.SpotifyClientSecret}
        SpotifyRefreshToken: !Sub ${StackParameters.Outputs.SpotifyRefreshToken}
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  StackLambdaTrackNowPlaying:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        CallbackURL: !Ref CallbackURL
        CurrentTrack: !Sub ${StackParameters.Outputs.CurrentTrack}
        PreviousEntryEpochTime: !Sub ${StackParameters.Outputs.PreviousEntryEpochTime}
        RedirectUri: !Ref CallbackURL
        SpotifyClientID: !Sub ${StackParameters.Outputs.SpotifyClientID}
        SpotifyClientSecret: !Sub ${StackParameters.Outputs.SpotifyClientSecret}
        SpotifyRefreshToken: !Sub ${StackParameters.Outputs.SpotifyRefreshToken}
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}

  StackLambdaReportCurrentMonth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://spotify-tracker-sam-stackbucket-t9la7txytz-bucket-17ayxd8l3bm8f.s3.amazonaws.com/serverless-function.yaml
      Parameters:
        Bucket: !Sub ${StackBucket.Outputs.Bucket}
        Table: !Ref DynamoDB
        Topic: !Sub ${StackTopics.Outputs.TopicARN}