AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Launch Template for Github Actions
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2'
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: None
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: A list of subnets for the Auto Scaling group
    Default: None

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: Github-Actions-CFT
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: t2.micro
        NetworkInterfaces:
          - DeviceIndex: 0
            DeleteOnTermination: true

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: GithubActionsCFT
      VpcId: !Ref VpcId

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # Non-Mixed Instance Policy
      #LaunchTemplate:
      #  LaunchTemplateId: !Ref LaunchTemplate
      #  Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      CapacityRebalance: false
      Cooldown: 60
      HealthCheckGracePeriod: 30
      MaxSize: '10'
      MinSize: '0'
      DesiredCapacity: '0'
      VPCZoneIdentifier: !Ref Subnets
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref LaunchTemplate
            Version: !GetAtt LaunchTemplate.LatestVersionNumber
        InstancesDistribution:
          OnDemandAllocationStrategy: lowest-price
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: lowest-price
          SpotInstancePools: 20