Description: Python Requests Layer

Parameters:
  Key:
    Type: String
    Default: None

Outputs:
  RequestsLayerArn:
    Value: !Ref Requests
    Export:
      Name: !Sub ${AWS::StackName}-RequestsLayerArn

Resources:
  Requests:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !ImportValue spotify-tracker-sam-Bucket
        S3Key: !Ref Key
      Description: Python Requests Layer (Built by Github Actions)