Description: Lambda Function POC

Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Lambda Function

Parameters:
  Table:
    Type: String
    Default: None
  Topic:
    Type: String
    Default: None

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: code
      Timeout: 840 # 14 minutes
      Environment:
        Variables:
          Table: !ImportValue spotify-tracker-sam-TableName
          TopicArn: !ImportValue spotify-tracker-sam-TopicArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue spotify-tracker-sam-TableName
        - Statement:
          - Effect: Allow
            Action:
              - 'sns:publish'
            Resource:
              - !ImportValue spotify-tracker-sam-TopicArn