# This is a basic workflow to help you get started with Actions

name: Export DynamoDB Table

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_run:
    workflows: [1-Main-Template]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::195663387853:role/github-oidc-Role-8FD7L07NDB33
          aws-region: us-east-1

      - name: SAM Build & Deploy Utilities/export-table
        working-directory: ./3_Utilities/export-table
        run: sam build && sam deploy
